### ISSUE TITLE
'meta' of undefined     

### ISSUE THREAD

**Issue by MatHackDev** [dword-design/nuxt-route-meta#106]
Hi everyone;

I have a problem with this plugin when i build my site. 

**Error : Cannot read property 'meta' of undefined** 

I have two solution : 
First: add object "meta: {}" in all pages (It's so bad)
Second:  Into the lib just change the line 139: "...data.meta" by "...data?.meta"

I while create a pull request for this bug.

Thanks :)

**Comment by dword-design** [comment]
@MatHackDev Should be fixed
