### ISSUE TITLE
remove direct git dependencies 

### ISSUE THREAD

**Issue by valeryi** [dword-design/nuxt-route-meta#108]
At the moment it's not working with all setups since the package requires git to be installed on the machine (docker)

Some setups need to apply some changes to the deploy pipelines. Not always it's a good idea to make changes in Kubernates because of one npm package (even if it's a very good one 😁🙄😉)

error example:
```
npm ERR! code ENOENT
npm ERR! syscall spawn git
npm ERR! path git
npm ERR! errno -2
npm ERR! enoent Error while executing:
npm ERR! enoent undefined ls-remote -h -t ssh://git@github.com/dword-design/dedent.git
npm ERR! enoent 
npm ERR! enoent 
npm ERR! enoent spawn git ENOENT
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 
```

Is it possible to remove direct git dependencies?

**Comment by dword-design** [comment]
Should work now. Feel free to reopen.

**Comment by valeryi** [comment]
Thanks a lot!
