### ISSUE TITLE
Doesn't work with typescript

### ISSUE THREAD

**Issue by alijaya** [dword-design/nuxt-route-meta#18]
It doesn't work well with typescript, it reports an error regarding typescript syntax

**Comment by dword-design** [comment]
@alijaya What is the error? Maybe we have to add a `types.d.ts` file? I'm actually not much into TypeScript yet, but I'm working on ot.

**Comment by alijaya** [comment]
Sorry I don't have example here.
But when I try to include this module, it gives me an error regarding the typescript syntax, in my case is like this:
`someFunction(param : number) {`

It gives an error highlighting `: number`, I think because it's not a valid javascript syntax, it's typescript syntax.

I'm wondering if this module trying to parse the file directly, if that is the case, that could be a problem if the parser only recognize javascript code.

**Comment by panvakalo** [comment]
same here. I use `nuxt-property-decorator` and I declare my components of the page like this
```
@Component({
   components: {
      ...
   }
})
```

I get the following error:
![image](https://user-images.githubusercontent.com/9567941/113995463-90ddda80-9856-11eb-9bad-5879009bc49f.png)

**Comment by dword-design** [comment]
@panvakalo Let's continue with the decorators here: https://github.com/dword-design/nuxt-route-meta/issues/2

**Comment by dword-design** [comment]
@panvakalo Write something into the linked issue so I can mention you.

**Comment by dword-design** [comment]
@alijaya Yeah that'll probably be the issue. I think we'd have to parse the file via typescript then.

**Comment by dword-design** [comment]
@alijaya I think it could be possible by detecting the lang property in vue files and then parsing it via TypeScript. Would open up complexity though for each transpiler.

**Comment by dword-design** [comment]
`nuxt-route-meta` supports TypeScript now 🥳.
