### ISSUE TITLE
Cannot read property 'type' of undefined

### ISSUE THREAD

**Issue by thommydz** [dword-design/nuxt-route-meta#22]
After installing and adding `'nuxt-route-meta',` to my nuxt.config.js, i cannot build my application anymore. 

Running `npm run dev` fails and says `Cannot read property 'type' of undefined`[](url)

complete error:

`ERROR  Cannot read property 'type' of undefined`

`  at toJs (node_modules\ast-to-literal\index.js:6:33)`
`  at node_modules\ast-to-literal\index.js:37:19`
`  at Array.reduce (<anonymous>)`
`  at computeProps (node_modules\ast-to-literal\index.js:30:16)`
`  at toJs (node_modules\ast-to-literal\index.js:15:10)`
`  at ExportDefaultDeclaration (node_modules\nuxt-route-meta\dist\index.js:43:92)`
`  at NodePath._call (node_modules\nuxt-route-meta\node_modules\@babel\traverse\lib\path\context.js:55:20)`
`  at NodePath.call (node_modules\nuxt-route-meta\node_modules\@babel\traverse\lib\path\context.js:42:17)`
`  at NodePath.visit (node_modules\nuxt-route-meta\node_modules\@babel\traverse\lib\path\context.js:92:31)`
`  at TraversalContext.visitQueue (node_modules\nuxt-route-meta\node_modules\@babel\traverse\lib\context.js:116:16)`
`  at TraversalContext.visitMultiple (node_modules\nuxt-route-meta\node_modules\@babel\traverse\lib\context.js:80:17)`
`  at TraversalContext.visit (node_modules\nuxt-route-meta\node_modules\@babel\traverse\lib\context.js:142:19)`
`  at Function.traverse.node (node_modules\nuxt-route-meta\node_modules\@babel\traverse\lib\index.js:82:17)`
`  at NodePath.visit (node_modules\nuxt-route-meta\node_modules\@babel\traverse\lib\path\context.js:99:18)`
`  at TraversalContext.visitQueue (node_modules\nuxt-route-meta\node_modules\@babel\traverse\lib\context.js:116:16)`
`  at TraversalContext.visitSingle (node_modules\nuxt-route-meta\node_modules\@babel\traverse\lib\context.js:85:19)`

**Comment by dword-design** [comment]
@thommydz Can you send me the page that contains the metadata? Sounds like some syntax that is unsupported yet.

**Comment by thommydz** [comment]
Thank you for your quick reply! 

I did not set up the metadata yet, because nuxt immediately fails on build after installation and adding it to nuxt.config.js.

Some things that might be related:
- I use a Axios plugin to set custom headers that is applied on every request/route
- I use a plugin that watches $route and fills a data object in root when "from" is defined.

Not sure of any of this is related to the problem. The thing is that as soon as I add `nuxt-route-meta` to my modules, it fails.

If you need any more details please let me know!

**Comment by dword-design** [comment]
@thommydz The module works by parsing all page files and then injecting data into the route meta properties. So the problem will be that one of your pages has some kind of syntax that the module doesn't know of. Chances are rather ok that it's easily fixable, I had these errors a couple of times. Question would be which page/syntax it is that breaks the thing.

**Comment by thommydz** [comment]
Allright thank you for your help! Now I know what to look for I'm sure I will find and fix it :-)

**Comment by azamat9904** [comment]
У меня такая же ошибка, не получается исправить

**Comment by ngongon** [comment]
@dword-design  Thanks for this library! I also experienced the same error. The thing was if there is no 'meta' property in component vue file, your parser generates errors. Please handle this. Also, I tried to figure out the problem by reading your codes, there was also another library of yours 'ast-to-literal'. And this library did not handle undefined object.

**Comment by dword-design** [comment]
@ngongon Thanks a lot for investigating! I cannot reproduce it though 😅. Checkout this minimal repo:
https://github.com/dword-design/test-nuxt-route-meta-type-undefined

**Comment by ngongon** [comment]
Ok I will try to check your test repo! I am now using current deployed nuxt-route-meta as such: all Pages must include meta property(even with subdirectory). It might help your investigation.(Maybe as test repo is just basic, I might try to creating more pages with nested directory and other component hooks)

**Comment by dword-design** [comment]
@ngongon Yeah it might. Best would probably be a publicly available repo or minimal failing example.

**Comment by ngongon** [comment]
I tried to reproduce with your minimal repo, but I failed. Also I tried to checkout to commit before I implemented nuxt-route-meta, it failed..(without initializing node_modules) might be related to adding package with existing other packages..

**Comment by dword-design** [comment]
@ngongon Alright. Let me know if there is something new. Also, if you have public code to share, feel free to post it here.

**Comment by furkan-guvenc** [comment]
I got this error also and it probably because of declaring pages with nuxt-composition-api defineComponent for me
