### ISSUE TITLE
yarn install Error

### ISSUE THREAD

**Issue by AShuiCoder** [dword-design/nuxt-route-meta#26]
![image](https://user-images.githubusercontent.com/47807522/114978605-00d60b80-9ebc-11eb-9a17-f2da5e127ee2.png)

**Comment by dword-design** [comment]
@AShuiCoder Works for me. Have you tried it again? Sounds a bit like a temporary GitHub issue. Also, which commands have you executed before that?

**Comment by AShuiCoder** [comment]
I install other packages are not wrong, just this.

**Comment by AShuiCoder** [comment]
use npm is ok, yarn error

**Comment by dword-design** [comment]
@AShuiCoder hm it's really weird. I tried it via GitHub actions windows again, but no problem:
https://github.com/dword-design/test-nuxt-route-meta-yarn-windows/runs/2373731551?check_suite_focus=true

**Comment by dword-design** [comment]
@AShuiCoder Try to clear the yarn cache via `yarn cache clean` and run it again. Maybe also throw away `yarn.lock` and run `yarn`.
