### ISSUE TITLE
Route meta is doesn't work in nested routes

### ISSUE THREAD

**Issue by sakandemir06** [dword-design/nuxt-route-meta#84]
Hello, I have a problem with route meta in nested routes, when I use <nuxt-child> route meta is doesn't work. I don't know what's wrong someone can help me?

My Pages Folder Structure;

-store
---basket
-----index.vue (meta doesn't work)
---category
-----_category
-------index.vue (meta doesn't work)
---index.vue (meta doesn't work)
-store.vue (meta works) (have only nuxt-child and asyncData functions)

**Comment by dword-design** [comment]
Hey @sakandemir06, I just added a test for subroutes but which seems to work without problems. Also, I'm a bit confused that you have your routes under the `store` folder, which is reserved for Vuex stores 😅. Maybe that's the issue?

**Comment by sakandemir06** [comment]
@dword-design Thanks for your answer, this structure is in the pages folder not in the store folder :)

like this;
pages
-store
--bla.bla bla

the "store" is mine route name :)

When I delete -store.vue all metas working fine, but when I create store.vue, nested metas not working, Did you try it?

**Comment by dword-design** [comment]
@sakandemir06 Yeah indeed wasn't implemented. Should work now.

**Comment by sakandemir06** [comment]
@dword-design It's work! Thank you for your fast support :)
